"""
Explicit entry point for guarded JARVIS self-modification.

The actual source edit is generated by the existing code helper, then routed
through core.self_modification so validation and human confirmation remain
mandatory.
"""

from __future__ import annotations

from core import self_modification


def self_modification_action(parameters: dict, player=None) -> str:
    p = parameters or {}
    action = str(p.get("action", "status")).strip().lower()

    if action == "status":
        return self_modification.status()

    if action in {"reject", "cancel"}:
        return self_modification.reject_pending()

    if action in {"rollback", "undo"}:
        return self_modification.rollback_last()

    if action in {"edit", "modify", "change"}:
        file_path = str(p.get("file", "")).strip()
        instruction = str(p.get("instruction", "")).strip()
        if not file_path or not instruction:
            return "Self-modification needs both file and instruction."
        from actions.code_helper import _edit_action
        return _edit_action(file_path, instruction, player, verify=True)

    return "Use action=edit, status, reject, or rollback."


TOOL = {
    "name": "self_modification",
    "description": (
        "Guarded JARVIS self-modification. Edit JARVIS source files only through "
        "a validated proposal and the human confirmation button on the HUD. "
        "Also supports status, rejecting a pending proposal, and rolling back "
        "a self-edit from the current undo stack. Never edits secrets or memory."
    ),
    "parameters": {
        "type": "OBJECT",
        "properties": {
            "action": {"type": "STRING", "description": "edit | status | reject | rollback"},
            "file": {"type": "STRING", "description": "JARVIS source path such as main.py or actions/foo.py"},
            "instruction": {"type": "STRING", "description": "Exact change requested"},
        },
        "required": ["action"],
    },
    "handler": self_modification_action,
}
